[package]
name = "cpp"
version = "0.1.0"
authors = ["Konrad Fabrtius Christensen <a>"]
edition = "2018"
build = "build.rs"

[dependencies]
game_lib = { path = "../game_lib"}
libc = "0.2"

[build-dependencies]
cc = "1.0"