[package]
name = "game"
version = "0.1.0"
authors = ["Konrad Fabrtius Christensen <a>"]
edition = "2018"

[dependencies]
game_lib = { path = "game_lib/"}

rand = "0.6"

strum = "0.13.0"
strum_macros = "0.13.0"

libc = "0.2.49"

cpp = { path = "cpp/"} 
rust = { path = "rust/"}

indicatif = "0.11.0"