[package]
name = "game"
version = "0.1.0"
authors = ["Konrad Fabrtius Christensen <a>"]
build = "build.rs"
edition = "2018"

[dependencies]
rand = "0.6"

strum = "0.13.0"
strum_macros = "0.13.0"

libc = "0.2.49"

[build-dependencies]
cc = "1.0"